# Generated by Django 5.2.9 on 2025-12-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='format',
            field=models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4')], default='mp4', max_length=5),
        ),
        migrations.AlterField(
            model_name='download',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='download',
            name='quality',
            field=models.CharField(default='best', max_length=10),
        ),
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
