# Generated by Django 5.2.9 on 2025-12-29 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_download_updated_at_alter_download_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='download',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for this download', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='quality_actual',
            field=models.CharField(blank=True, help_text='Actual quality downloaded (may differ from requested)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='format',
            field=models.CharField(choices=[('mp3', 'MP3 Audio'), ('mp4', 'MP4 Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='download',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['user', 'status'], name='downloader__user_id_c98e59_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['created_at'], name='downloader__created_0e06a9_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['status'], name='downloader__status_52be73_idx'),
        ),
        migrations.AlterModelTable(
            name='download',
            table='downloader_downloads',
        ),
    ]
