# Generated by Django 5.2.9 on 2025-12-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_alter_download_options_download_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='quality_actual',
            field=models.CharField(blank=True, help_text='Actual quality downloaded', max_length=10, null=True),
        ),
    ]
