# Generated by Django 5.2.9 on 2026-01-07 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_alter_download_celery_task_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['celery_task_id'], name='idx_celery_task'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_created'),
        ),
    ]
