# Generated by Django 5.2.9 on 2026-01-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_download_idx_celery_task_download_idx_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='queued', max_length=20),
        ),
    ]
