# Generated by Django 5.2.9 on 2026-01-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_alter_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
