# Generated by Django 5.2.9 on 2026-01-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_alter_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='download',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
